
package juddi.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FlightService", targetNamespace = "http://client.juddi/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlightService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<juddi.client.Flight>
     * @throws SQLTransactionException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFlights", targetNamespace = "http://client.juddi/", className = "juddi.client.GetFlights")
    @ResponseWrapper(localName = "getFlightsResponse", targetNamespace = "http://client.juddi/", className = "juddi.client.GetFlightsResponse")
    @Action(input = "http://client.juddi/FlightService/getFlightsRequest", output = "http://client.juddi/FlightService/getFlightsResponse", fault = {
        @FaultAction(className = SQLTransactionException.class, value = "http://client.juddi/FlightService/getFlights/Fault/SQLTransactionException")
    })
    public List<Flight> getFlights(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws SQLTransactionException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLTransactionException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changeFlight", targetNamespace = "http://client.juddi/", className = "juddi.client.ChangeFlight")
    @ResponseWrapper(localName = "changeFlightResponse", targetNamespace = "http://client.juddi/", className = "juddi.client.ChangeFlightResponse")
    @Action(input = "http://client.juddi/FlightService/changeFlightRequest", output = "http://client.juddi/FlightService/changeFlightResponse", fault = {
        @FaultAction(className = SQLTransactionException.class, value = "http://client.juddi/FlightService/changeFlight/Fault/SQLTransactionException")
    })
    public String changeFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws SQLTransactionException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLTransactionException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteFlight", targetNamespace = "http://client.juddi/", className = "juddi.client.DeleteFlight")
    @ResponseWrapper(localName = "deleteFlightResponse", targetNamespace = "http://client.juddi/", className = "juddi.client.DeleteFlightResponse")
    @Action(input = "http://client.juddi/FlightService/deleteFlightRequest", output = "http://client.juddi/FlightService/deleteFlightResponse", fault = {
        @FaultAction(className = SQLTransactionException.class, value = "http://client.juddi/FlightService/deleteFlight/Fault/SQLTransactionException")
    })
    public String deleteFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws SQLTransactionException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws SQLTransactionException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFlight", targetNamespace = "http://client.juddi/", className = "juddi.client.AddFlight")
    @ResponseWrapper(localName = "addFlightResponse", targetNamespace = "http://client.juddi/", className = "juddi.client.AddFlightResponse")
    @Action(input = "http://client.juddi/FlightService/addFlightRequest", output = "http://client.juddi/FlightService/addFlightResponse", fault = {
        @FaultAction(className = SQLTransactionException.class, value = "http://client.juddi/FlightService/addFlight/Fault/SQLTransactionException")
    })
    public int addFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws SQLTransactionException
    ;

}
