
package juddi.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SQLTransactionException", targetNamespace = "http://client.juddi/")
public class SQLTransactionException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SqlFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SQLTransactionException(String message, SqlFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SQLTransactionException(String message, SqlFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: juddi.client.SqlFault
     */
    public SqlFault getFaultInfo() {
        return faultInfo;
    }

}
